---
volumes:
  zigbee2mqtt-data:
    labels:
      net.mafro.kopia: true

networks:
  caddy:
    external: true

services:
  z2m:
    image: koenkk/zigbee2mqtt:${ZIGBEE2MQTT_VERSION}
    restart: unless-stopped
    networks:
      - default
      - caddy
    extra_hosts:
      locke: 192.168.1.198
      zigstargw: 192.168.1.42
    environment:
      - TZ=Australia/Melbourne
    volumes:
      - zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
      - ./zigbee2mqtt.yaml:/app/data/configuration.yaml
    labels:
      caddy: zigbee2mqtt.mafro.net
      caddy.tls.ca: https://ca.mafro.net:4433/acme/acme/directory
      caddy.tls.ca_root: /root/step_ca.crt
      caddy.reverse_proxy: "{{upstreams 8080}}"
