---
version: '3'

volumes:
  zigbee2mqtt-data: {}

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    ports:
      - 8787:8080
    environment:
      - TZ=Australia/Melbourne
    devices:
      - /dev/ttyAMA0
      - /dev/ttyS0
    volumes:
      - zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
      - ./zigbee2mqtt.yaml:/app/data/configuration.yaml
