---
version: '3'

volumes:
  zigbee2mqtt-data: {}

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    ports:
      - 8787:8080
    extra_hosts:
      locke: 192.168.1.198
      zigstargw: 192.168.1.241
    environment:
      - TZ=Australia/Melbourne
    volumes:
      - zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
      - ./zigbee2mqtt.yaml:/app/data/configuration.yaml
