homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://locke
serial:
  port: tcp://zigstargw:6638
  adapter: zstack
frontend:
  enabled: true
  port: 8080
advanced:
  channel: 11
  pan_id: 35471
  ext_pan_id:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  network_key:
    - 18
    - 6
    - 138
    - 101
    - 89
    - 70
    - 168
    - 237
    - 224
    - 86
    - 113
    - 226
    - 103
    - 218
    - 119
    - 188
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  cache_state_persistent: true
  cache_state_send_on_startup: true
device_options: {}
devices:
  '0xa4c1386a74140d98':
    friendly_name: TV Corner
  '0x804b50fffe432925':
    friendly_name: Kitchen Sink
  '0x804b50fffeb2185b':
    friendly_name: Kitchen Corner
    state_action: false
  '0x84fd27fffe543ac3':
    friendly_name: Laundry
  '0xa4c138ca3309c102':
    friendly_name: Middle Sofa
  '0xa4c1387509370cec':
    friendly_name: Snug Lamp
  '0xa4c1386293327df7':
    friendly_name: Office Lamp
    state_action: true
  '0xf4b3b1fffe9b89e3':
    friendly_name: Kitchen Counter Switch
  '0x2c1165fffebaa483':
    friendly_name: Repeater
  '0xa4c1387e76a5d34d':
    friendly_name: Big Lamp
  '0xa4c138b2b03ba312':
    friendly_name: Madeleine Bedroom
  '0x001788010df600a9':
    friendly_name: Hallway Sensor
  '0xa49e69fffef0ff2d':
    friendly_name: Madeleine Door Switch
  '0xf4b3b1fffe8820bb':
    friendly_name: Madeleine Bed Switch
  '0x00158d00051e8412':
    friendly_name: Bathroom Sensor
  '0x0c4314fffefdba1d':
    friendly_name: Upstairs Bedside Switch
  '0xa4c13838020a4f9b':
    friendly_name: Laundry Sensor
  '0x6c5cb1fffe0cdbe4':
    friendly_name: Office Lamp Switch
  '0x001788010df5feef':
    friendly_name: Living Room Sensor
groups:
  '1':
    friendly_name: Kitchen Counter
version: 4
