homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://locke
serial:
  port: tcp://zigstargw:6638
frontend:
  port: 8080
advanced:
  channel: 11
  pan_id: 35471
  ext_pan_id:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  network_key:
    - 18
    - 6
    - 138
    - 101
    - 89
    - 70
    - 168
    - 237
    - 224
    - 86
    - 113
    - 226
    - 103
    - 218
    - 119
    - 188
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
devices:
  '0xa4c1386a74140d98':
    friendly_name: '0xa4c1386a74140d98'
